spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: ${JDBC_DATABASE_DRIVER_CLASS_NAME}
  jpa:
    database: ${JPA_DATABASE}
    show-sql: ${JPA_SHOW_SQL}
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
  jackson:
    serialization:
      fail-on-empty-beans: false
anski:
  app:
    jwtSecret: secret
    jwtExpirationMs: 86400000